config/routes.rb
DemoApp::Application.routes.draw do
resources :microposts, :only => [:create,:destroy]
resources :sessions, :only => [:new, :create, :destroy]
match '/signin', :to => 'sessions#new'
match '/signout', :to => 'sessions#destroy'
 match'/contact',:to =>'pages#contact'
 match'/about',:to =>'pages#about'
 match'/help',:to =>'pages#help'
match'signup',:to=>'users#new'
  root:to=>'pages#home'
	resources:users

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content
	belongs_to :user
	validates :content, :presence =>true, :length => {:maximum => 140}
	validates :user_id, :presence =>true
	default_scope :order => 'microposts.created_at DESC'
end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base
  attr_accessible :email, :name
	attr_accessor :password
	attr_accessible :email, :name, :password, :password_confirmation
	has_many :microposts, :dependent => :destroy
	
	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :name, :presence => true, 
			:length => { :maximum =>50 }
	validates :email,:presence => true, 
		       	:format => { :with => email_regex },
			:uniqueness => {:case_sensitive => false}
	validates :password, :presence => true,
			     :confirmation => true,
			     :length => {:within => 6..40 }	
  before_save :encrypt_password

	def has_password?(submitted_password)
		encrypted_password == encrypt(submitted_password)
	end

	def self.authenticate(email, submitted_password)
	  user = find_by_email(email)
	  return nil if user.nil?
	  return user if user.has_password?(submitted_password)
	  
	  return nil
	end	

	private
	def encrypt_password
		self.encrypted_password = encrypt(password)	
	end
	def encrypt(string)
		Digest::SHA2.hexdigest(string)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
before_filter :authenticate, :only => [:create, :destroy]
before_filter :authorized_user, :only => [:destroy]
  private
  def authenticate
    if current_user.nil?
	redirect_to signin_path, :notice => "Please sign in"
    end
  end
  
  def authorized_user
    @micropost = Mcropost.find(params[:id])
    if @micropost.user != current_user
	redirect_to root_path
  end
end


  public
	def create
	  @micropost = current_user.microposts.build(params[:micropost])
	  if @micropost.save
		flash[:success] = "Micropost created"
		redirect_to root_path
	  else
	        render 'pages/home'
	  end
	end
	
	def destroy
	  @micropost.destroy
	  redirect_to root_path
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
	@title="Home"
	@micropost =Micropost.new if !current_user.nil?
	
  end

  def contact
	@title="Contact"  
end

  def about
	@title="About"
  end

  def help
	@title="Help"
	
end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		@title = "Sign In"
	end
	
        def create
	user = User.authenticate(params[:session][:email], params[:session][:password])
	  if user.nil?
	    flash.now[:error] ="Invalid email or password."
	    @title ="Sign in"
	    render "new"
	  else 
	    sign_in user
	    redirect_to root_path
	    # redirect to the user's show page.
	  end
	end
	def destroy
	  sign_out
	  redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_filter :authenticate, :only => [:edit, :update, :destroy]
	private
	
	def authenticate
	  if current_user.nil?
	  redirect_to signin_path, :notice =>"Please sign in"
	else
	  user =User.find(params[:id])
	  if user != current_user
	    redirect_to root_path,
	  :notice =>"Editing other users is not allowed."
	  end
	end
	end
public
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
        @user = User.find(params[:id])
	@microposts = @user.microposts
	@title = @user.name
   # respond_to do |format|
     # format.html # show.html.erb
      #format.json { render json: @user }
  #  end
end


  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
   
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    	@user = User.new(params[:user])
	
      if @user.save
	
	sign_in @user
       redirect_to @user
	
      else
        @title ="Sign up"
	render "new"
      end
    end


  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
	def sign_in(user)
	  cookies.signed[:remember_token] = user.id
	  @current_user = user
	end
	
	def current_user
	  if @current_user.nil?
	    user_id=cookies.signed[:remember_token]
	    user=User.find_by_id(user_id)
	  else
	    @current_user
	  end
	end
	
	def sign_out
	  cookies.delete(:remember_token)
	  @current_user = nil	
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
	<nav class = "round" >
		<ul>
			<li><%= link_to "About",about_path %> </li>
			<li><%= link_to "Contact",contact_path %> </li>
			<li> <a href="http://news.railstutorial.org/">News</a></li>
			<li> <a href="http://www.railstutorial.org/">Rails Tutorialss</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<% logo = image_tag("logo.png", :alt => "Demo App",:class => "round")%>
	<%= link_to logo,root_path %>	
	<nav class ="round">
		<ul>
			<li><%= link_to "Home",root_path %> </li> 
			<li><%= link_to "Help", help_path %> </li>
		  	<% if current_user.nil? %>
			<li> <%= link_to "Sign in", signin_path %></li>
			<% else %>
			<li> <%= link_to "Sign out", signout_path %></li>
			<% end %>
		</ul>
	</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<stylesheets>
	<nav class="round">
	</nav>
</stylesheets>
		

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

    <head>
        <title><%= @title %></title>
	<%= javascript_include_tag "application" %>
        <%=csrf_meta_tag %>
  	
	<%=stylesheet_link_tag'blueprint/screen',:media=>'screen'%>
	<%=stylesheet_link_tag'blueprint/print',:media=>'print'%>
	<%=stylesheet_link_tag'custom',:media=>'screen'%>
	
    </head>
	<body>
	<div class="container">
	<%= render 'layouts/header' %>
		<section class='round'>
	<% flash.each do |key, value| %>
		<div class="flash <%= key %>"><%= value %></div>
		<% end %>
              <%= yield %>
	</section>
	  <%=render 'layouts/footer' %>
  	 
	</div> 
	</body>
</html>

app/views/microposts/_micropost.html.erb
<tr>
  <td class="micropost">
    <span class="content"><%= micropost.content %></span>
    <span class="timestamp">
	Posted at <%= micropost.created_at %>
	<% if current_user == micropost.user %>
	  <%= link_to "Delete",micropost, :method => :delete,
						  :confirm => "Are you sure?",	
						:title => micropost.content %>

	<% end %>
    </span>
  </td>
</tr>

app/views/pages/about.html.erb
<h1>About us</h1>
	<p>	
	<a href="http://guarded-tundra-49432.herokuapp.com">Demo app<a>
	is a project to make a book and screencasts to teach web debelopment
	<a href="http://railstutorial.org/">Ruby on Rails</a>.This
	is the sample application for http://railstutorial.org/
	
	</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.erb
<h1>help</h1>
	<p>if you get any question,contact us by email: 2385249460@qq.com</p>

app/views/pages/home.html.erb
<% if current_user.nil? %>
	<p>This is the home page for my demo app.</p>
	<%= link_to 'Sign up now!', signup_path, :class => 'signup_button round' %>
<% else %>
	<table class="front">
	  <tr>
	    <td class="main">
		<h1 class="micropost">What's up</h1>
		<%= form_for(@micropost) do |f| %>
		  <div class="field">
		    <%= f.text_area :content %>
		  </div>
		  <div class="actions" %>	
		    <%= f.submit "Submit" %>
		  </div>
		<% end %>
	    <td class="sidebar round">
		<a href="<%= user_path(current_user) %>"><%= current_user.name %></a>
		<br/>Microposts: <%=current_user.microposts.count %>
	    </td>
	  </tr>
	<% end %>
	<%= link_to "Show all users", users_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<table class="profile">
  <tr>
    <td class="main">
	<h1>
	  <%= @user.name %>
	</h1>
	  <% if !@user.microposts.empty? %>
	    <table class="microposts">
	      <%= render @microposts %>
	    </table>
	  <% end %>
    </td>
    <td class="sidebar round">
	<strong>Name</strong> <%= @user.name %><br/>
	<strong>Email</strong> <%= @user.email %><br/>
	<strong>URL</strong> <%= link_to user_path(@user),@user %><br/>
	<strong>Microposts</strong> <%= @user.microposts.count %>
	<% if current_user == @user %>
	  <br/>
	  <%= link_to "Edit My Info", edit_user_path(@user) %>
	<% end %>
    </td>
  </tr>
</table>
<p id="notice"><%= notice %></p>
<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>